# Version of the docker-compose file format
version: '3'

# Individual components of the overall product (the web app and the compiler api)
services:
    compiler:
        # Configuration options applied at build time (i.e., location of Dockerfile)
        build: ./compiler

    app:
        # Configuration options applied at build time (i.e., location of Dockerfile)
        build: ./app
        # Starts services in dependency order, i.e., compiler before app
        depends_on:
            - compiler
